apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: clickhouse-network-partition-chaos
  namespace: vat-staging
  labels:
    app.kubernetes.io/name: clickhouse-chaos
    app.kubernetes.io/part-of: vat-enterprise
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - vat-staging
    labelSelectors:
      app.kubernetes.io/name: vat-clickhouse
  direction: both
  target:
    selector:
      namespaces:
        - vat-staging
      labelSelectors:
        app.kubernetes.io/name: vat-redpanda
    mode: all
  duration: "60s"
